theme: minima
title: welcome to vanessa's website
author: vanessa b
description: > # this means to ignore newlines until "baseurl:"
  beep boop

# social links
github_username:  vbayubaskoro # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
